#! /bin/sh

### BEGIN INIT INFO
# Provides:          omxplayer-service
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start omxplayer-service script
# Description:       Starts omxplayer-executor.bash script at boot 
### END INIT INFO

case "$1" in
  start)
    echo "Starting omxplayer-service"
    screen -d -m -S "omxplayer-service" /usr/local/bin/omxplayer-executor.bash
    ;;
  stop)
    echo "Stopping omxplayer-service"
    screen -X -S "omxplayer-service" kill
    ;;
  *)
    echo "Usage: /etc/init.d/omxplayer-service {start|stop}"
    exit 1
    ;;
esac

exit 0 


